import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Civic SDK In Action</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         <a>Hi! I'm Drea from Civic!</a>
        </h1>

        <p className={styles.description}>
          Get started by searching for my wallet{' '}
          <code className={styles.code}>AuTum18SCaLNU6widaL891dCjFMsPGUf7KLmDf6L5uCz</code>
        </p>
      
        <form action="/profile" method='get'>
          <input placeholder='Enter Address' name='address' />
        </form>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {''}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
